### ISSUE TITLE
Doesn't add to blocklist

### ISSUE THREAD

**Issue by rapdactyl** [RoyRiv3r/One-Click-Bluesky-Blocker#1]
When attempting to use this extension on Firefox 133, I get the error message "Error blocking [user]." The user then doesn't show up on my block list, the only result seems to be that the post is removed from my feed which is undone on refresh.
![image](https://github.com/user-attachments/assets/217de840-4667-4d0a-a239-0e0ed5d84d03) (the user here is random)

This is the only bluesky-related extension I'm using. Let me know if there's something specific I can do to help narrow down the issue, and thanks for your work on this extension!

**Comment by RoyRiv3r** [comment]
I suspect that something is blocking access to One Click Bluesky Blocker, could you try installing the add-on via incognito mode without any other addons enabled? If it's working then I may have to change how to retrieve the info (@username etc) to make it work properly.

**Comment by RoyRiv3r** [comment]
I have pushed an update ( 1.0.4 ) let me know if it's working.

**Comment by rapdactyl** [comment]
> I suspect that something is blocking access to One Click Bluesky Blocker, could you try installing the add-on via incognito mode without any other addons enabled? If it's working then I may have to change how to retrieve the info (@username etc) to make it work properly.

I set up a profile with no extensions and added One Click Bluesky Blocker, no dice, still running into the same error.

Having the same luck with the new version, on my regular profile and the blank one. Is there a log file or something I can dig up that would help identify what's going wrong?

**Comment by RoyRiv3r** [comment]
Yes it should be possible to see the logging error, try to press press ctrl + shift + J, a window should appear, click on multiprocess tab, if you don't see anything press CTRL + SHIFT + L, there you will see bunch of information, go to the bluesky website, clean the window, then press the block button, you'll see the action performed, errors if there are any and the info. 
There are not many logging info but should be enough I think, i'll push another update for more if needed.

**Comment by rapdactyl** [comment]
> Yes it should be possible to see the logging error, try to press press ctrl + shift + J, a window should appear, click on multiprocess tab, if you don't see anything press CTRL + SHIFT + L, there you will see bunch of information, go to the bluesky website, clean the window, then press the block button, you'll see the action performed, errors if there are any and the info.
> There are not many logging info but should be enough I think, i'll push another update for more if needed.

This is from the empty profile. I opened a new page to a specific bluesky profile and attempted to use the extension (hitting the red X on a post.) As soon as I did the red error from this screenshot came up, let me know if you need more of the log
![image](https://github.com/user-attachments/assets/44448615-50e9-4c3c-bdc8-549f0b3ec9d6)

This is the specific error:
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://chanterelle.us-west.host.bsky.network/xrpc/app.bsky.actor.getProfile?actor=dieworkwear.bsky.social. (Reason: CORS header ‘Origin’ cannot be added).`

**Comment by RoyRiv3r** [comment]
That's not it, try to press ctrl + shift + L on the web page, then refresh again.

**Comment by rapdactyl** [comment]
Ctrl+Shift+L doesn't seem to do anything. 

I did try with ctrl+shift+J again after figuring out how to clear the log so it wasn't a million lines. This is from right after the refresh to using the tool:
`Browser Console Mode
Parent process only(Fast)
Multiprocess(Slower)
Referrer Policy: Ignoring the less restricted referrer policy “origin-when-cross-origin” for the cross-site request: https://chanterelle.us-west.host.bsky.network/xrpc/app.bsky.notification.listNotifications?limit=40 [app.bsky.notification.listNotifications](https://chanterelle.us-west.host.bsky.network/xrpc/app.bsky.notification.listNotifications?limit=40)
Cookie warnings 2
Logging is enabled. [index.js:1:8132](moz-extension://1291e947-a461-4651-a346-71bf572e0991/index.js)
Initializing block button injection. [index.js:1:13685](moz-extension://1291e947-a461-4651-a346-71bf572e0991/index.js)
Referrer Policy: Ignoring the less restricted referrer policy “origin-when-cross-origin” for the cross-site request: https://bsky.social/xrpc/com.atproto.server.getSession [com.atproto.server.getSession](https://bsky.social/xrpc/com.atproto.server.getSession)
Referrer Policy: Ignoring the less restricted referrer policy “origin-when-cross-origin” for the cross-site request: https://statsigapi.net/v1/sdk_exception [sdk_exception](https://statsigapi.net/v1/sdk_exception)
Referrer Policy: Ignoring the less restricted referrer policy “origin-when-cross-origin” for the cross-site request: https://chanterelle.us-west.host.bsky.network/xrpc/chat.bsky.convo.listConvos?limit=1 [chat.bsky.convo.listConvos](https://chanterelle.us-west.host.bsky.network/xrpc/chat.bsky.convo.listConvos?limit=1)
Referrer Policy: Ignoring the less restricted referrer policy “origin-when-cross-origin” for the cross-site request: https://chanterelle.us-west.host.bsky.network/xrpc/app.bsky.notification.listNotifications?limit=40 [app.bsky.notification.listNotifications](https://chanterelle.us-west.host.bsky.network/xrpc/app.bsky.notification.listNotifications?limit=40)
Referrer Policy: Ignoring the less restricted referrer policy “origin-when-cross-origin” for the cross-site request: https://chanterelle.us-west.host.bsky.network/xrpc/app.bsky.actor.getPreferences [app.bsky.actor.getPreferences](https://chanterelle.us-west.host.bsky.network/xrpc/app.bsky.actor.getPreferences)
Referrer Policy: Ignoring the less restricted referrer policy “origin-when-cross-origin” for the cross-site request: https://chanterelle.us-west.host.bsky.network/xrpc/app.bsky.labeler.getServices?dids=did%3Aplc%3Aar7c4by46qjdydhdevvrndac&detailed=true [app.bsky.labeler.getServices](https://chanterelle.us-west.host.bsky.network/xrpc/app.bsky.labeler.getServices?dids=did%3Aplc%3Aar7c4by46qjdydhdevvrndac&detailed=true)
Referrer Policy: Ignoring the less restricted referrer policy “origin-when-cross-origin” for the cross-site request: https://chanterelle.us-west.host.bsky.network/xrpc/chat.bsky.convo.listConvos?limit=20 [chat.bsky.convo.listConvos](https://chanterelle.us-west.host.bsky.network/xrpc/chat.bsky.convo.listConvos?limit=20)
Referrer Policy: Ignoring the less restricted referrer policy “origin-when-cross-origin” for the cross-site request: https://chanterelle.us-west.host.bsky.network/xrpc/com.atproto.identity.resolveHandle?handle=dieworkwear.bsky.social [com.atproto.identity.resolveHandle](https://chanterelle.us-west.host.bsky.network/xrpc/com.atproto.identity.resolveHandle?handle=dieworkwear.bsky.social)
Referrer Policy: Ignoring the less restricted referrer policy “origin-when-cross-origin” for the cross-site request: https://chanterelle.us-west.host.bsky.network/xrpc/app.bsky.actor.getProfile?actor=did%3Aplc%3A4g43jcw5qenpylbkfulfjgii [app.bsky.actor.getProfile](https://chanterelle.us-west.host.bsky.network/xrpc/app.bsky.actor.getProfile?actor=did%3Aplc%3A4g43jcw5qenpylbkfulfjgii)
Referrer Policy: Ignoring the less restricted referrer policy “origin-when-cross-origin” for the cross-site request: https://chanterelle.us-west.host.bsky.network/xrpc/app.bsky.feed.getFeedGenerators?feeds=at%3A%2F%2Fdid%3Aplc%3Az72i7hdynmk6r22z27h6tvur%2Fapp.bsky.feed.generator%2Fwhats-hot&feeds=at%3A%2F%2Fdid%3Aplc%3Ajcoy7v3a2t4rcfdh6i4kza25%2Fapp.bsky.feed.generator%2Fastro&feeds=at%3A%2F%2Fdid%3Aplc%3Aq6gjnaw2blty4crticxkmujt%2Fapp.bsky.feed.generator%2Fcv%3Acat&feeds=at%3A%2F%2Fdid%3Aplc%3Az72i7hdynmk6r22z27h6tvur%2Fapp.bsky.feed.generator%2Fwith-friends&feeds=at%3A%2F%2Fdid%3Aplc%3Akkf4naxqmweop7dv4l2iqqf5%2Fapp.bsky.feed.generator%2Fverified-news&feeds=at%3A%2F%2Fdid%3Aplc%3Alptjvw6ut224kwrj7ub3sqbe%2Fapp.bsky.feed.generator%2Faaaotfjzjplna&feeds=at%3A%2F%2Fdid%3Aplc%3Ajfhpnnst6flqway4eaeqzj2a%2Fapp.bsky.feed.generator%2Ffor-science&feeds=at%3A%2F%2Fdid%3Aplc%3Ay7crv2yh74s7qhmtx3mvbgv5%2Fapp.bsky.feed.generator%2Fart-new&feeds=at%3A%2F%2Fdid%3Aplc%3Atenurhgjptubkk5zf5qhi3og%2Fapp.bsky.feed.generator%2Fdiscover&feeds=at%3A%2F%2Fdid%3Aplc%3Aodqmsar3ikz5ubokya4sempk%2Fapp.bsky.feed.generator%2Faaahudddd6mww&feeds=at%3A%2F%2Fdid%3Aplc%3Avjyot2w7zeomrslomwpfxirl%2Fapp.bsky.feed.generator%2Faaabucto6sdf6&feeds=at%3A%2F%2Fdid%3Aplc%3Az72i7hdynmk6r22z27h6tvur%2Fapp.bsky.feed.generator%2Fhot-classic&feeds=at%3A%2F%2Fdid%3Aplc%3Az72i7hdynmk6r22z27h6tvur%2Fapp.bsky.feed.generator%2Fbsky-team&feeds=at%3A%2F%2Fdid%3Aplc%3Awzsilnxf24ehtmmc3gssy5bu%2Fapp.bsky.feed.generator%2Fnewskies&feeds=at%3A%2F%2Fdid%3Aplc%3Ajdkvwye2lf4mingzk7qdebzc%2Fapp.bsky.feed.generator%2Ffurry-hot&feeds=at%3A%2F%2Fdid%3Aplc%3Aq6gjnaw2blty4crticxkmujt%2Fapp.bsky.feed.generator%2Ffirehose&feeds=at%3A%2F%2Fdid%3Aplc%3Ajfhpnnst6flqway4eaeqzj2a%2Fapp.bsky.feed.generator%2Fdiscourse&feeds=at%3A%2F%2Fdid%3Aplc%3A4jrld6fwpnwqehtce56qshzv%2Fapp.bsky.feed.generator%2Fgame-dev [app.bsky.feed.getFeedGenerators](https://chanterelle.us-west.host.bsky.network/xrpc/app.bsky.feed.getFeedGenerators?feeds=at%3A%2F%2Fdid%3Aplc%3Az72i7hdynmk6r22z27h6tvur%2Fapp.bsky.feed.generator%2Fwhats-hot&feeds=at%3A%2F%2Fdid%3Aplc%3Ajcoy7v3a2t4rcfdh6i4kza25%2Fapp.bsky.feed.generator%2Fastro&feeds=at%3A%2F%2Fdid%3Aplc%3Aq6gjnaw2blty4crticxkmujt%2Fapp.bsky.feed.generator%2Fcv%3Acat&feeds=at%3A%2F%2Fdid%3Aplc%3Az72i7hdynmk6r22z27h6tvur%2Fapp.bsky.feed.generator%2Fwith-friends&feeds=at%3A%2F%2Fdid%3Aplc%3Akkf4naxqmweop7dv4l2iqqf5%2Fapp.bsky.feed.generator%2Fverified-news&feeds=at%3A%2F%2Fdid%3Aplc%3Alptjvw6ut224kwrj7ub3sqbe%2Fapp.bsky.feed.generator%2Faaaotfjzjplna&feeds=at%3A%2F%2Fdid%3Aplc%3Ajfhpnnst6flqway4eaeqzj2a%2Fapp.bsky.feed.generator%2Ffor-science&feeds=at%3A%2F%2Fdid%3Aplc%3Ay7crv2yh74s7qhmtx3mvbgv5%2Fapp.bsky.feed.generator%2Fart-new&feeds=at%3A%2F%2Fdid%3Aplc%3Atenurhgjptubkk5zf5qhi3og%2Fapp.bsky.feed.generator%2Fdiscover&feeds=at%3A%2F%2Fdid%3Aplc%3Aodqmsar3ikz5ubokya4sempk%2Fapp.bsky.feed.generator%2Faaahudddd6mww&feeds=at%3A%2F%2Fdid%3Aplc%3Avjyot2w7zeomrslomwpfxirl%2Fapp.bsky.feed.generator%2Faaabucto6sdf6&feeds=at%3A%2F%2Fdid%3Aplc%3Az72i7hdynmk6r22z27h6tvur%2Fapp.bsky.feed.generator%2Fhot-classic&feeds=at%3A%2F%2Fdid%3Aplc%3Az72i7hdynmk6r22z27h6tvur%2Fapp.bsky.feed.generator%2Fbsky-team&feeds=at%3A%2F%2Fdid%3Aplc%3Awzsilnxf24ehtmmc3gssy5bu%2Fapp.bsky.feed.generator%2Fnewskies&feeds=at%3A%2F%2Fdid%3Aplc%3Ajdkvwye2lf4mingzk7qdebzc%2Fapp.bsky.feed.generator%2Ffurry-hot&feeds=at%3A%2F%2Fdid%3Aplc%3Aq6gjnaw2blty4crticxkmujt%2Fapp.bsky.feed.generator%2Ffirehose&feeds=at%3A%2F%2Fdid%3Aplc%3Ajfhpnnst6flqway4eaeqzj2a%2Fapp.bsky.feed.generator%2Fdiscourse&feeds=at%3A%2F%2Fdid%3Aplc%3A4jrld6fwpnwqehtce56qshzv%2Fapp.bsky.feed.generator%2Fgame-dev)
Referrer Policy: Ignoring the less restricted referrer policy “origin-when-cross-origin” for the cross-site request: https://chanterelle.us-west.host.bsky.network/xrpc/app.bsky.graph.getList?list=at%3A%2F%2Fdid%3Aplc%3Anhytley6vv7tq6k2at6kvl5b%2Fapp.bsky.graph.list%2F3kfxmmhwunt2a&limit=1 [app.bsky.graph.getList](https://chanterelle.us-west.host.bsky.network/xrpc/app.bsky.graph.getList?list=at%3A%2F%2Fdid%3Aplc%3Anhytley6vv7tq6k2at6kvl5b%2Fapp.bsky.graph.list%2F3kfxmmhwunt2a&limit=1)
Referrer Policy: Ignoring the less restricted referrer policy “origin-when-cross-origin” for the cross-site request: https://chanterelle.us-west.host.bsky.network/xrpc/app.bsky.actor.getProfile?actor=did%3Aplc%3Aks3gpa6ftoyaq7hmf6c4qx4c [app.bsky.actor.getProfile](https://chanterelle.us-west.host.bsky.network/xrpc/app.bsky.actor.getProfile?actor=did%3Aplc%3Aks3gpa6ftoyaq7hmf6c4qx4c)
Referrer Policy: Ignoring the less restricted referrer policy “origin-when-cross-origin” for the cross-site request: https://chanterelle.us-west.host.bsky.network/xrpc/app.bsky.graph.getActorStarterPacks?actor=did%3Aplc%3Aks3gpa6ftoyaq7hmf6c4qx4c&limit=10 [app.bsky.graph.getActorStarterPacks](https://chanterelle.us-west.host.bsky.network/xrpc/app.bsky.graph.getActorStarterPacks?actor=did%3Aplc%3Aks3gpa6ftoyaq7hmf6c4qx4c&limit=10)
Referrer Policy: Ignoring the less restricted referrer policy “origin-when-cross-origin” for the cross-site request: https://chanterelle.us-west.host.bsky.network/xrpc/chat.bsky.convo.getLog?cursor=2222222iofbk2 [chat.bsky.convo.getLog](https://chanterelle.us-west.host.bsky.network/xrpc/chat.bsky.convo.getLog?cursor=2222222iofbk2)
Referrer Policy: Ignoring the less restricted referrer policy “origin-when-cross-origin” for the cross-site request: https://chanterelle.us-west.host.bsky.network/xrpc/chat.bsky.convo.getConvoForMembers?members=did%3Aplc%3Aks3gpa6ftoyaq7hmf6c4qx4c [chat.bsky.convo.getConvoForMembers](https://chanterelle.us-west.host.bsky.network/xrpc/chat.bsky.convo.getConvoForMembers?members=did%3Aplc%3Aks3gpa6ftoyaq7hmf6c4qx4c)
Referrer Policy: Ignoring the less restricted referrer policy “origin-when-cross-origin” for the cross-site request: https://chanterelle.us-west.host.bsky.network/xrpc/app.bsky.feed.getAuthorFeed?actor=did%3Aplc%3Aks3gpa6ftoyaq7hmf6c4qx4c&filter=posts_and_author_threads&includePins=true&limit=30 [app.bsky.feed.getAuthorFeed](https://chanterelle.us-west.host.bsky.network/xrpc/app.bsky.feed.getAuthorFeed?actor=did%3Aplc%3Aks3gpa6ftoyaq7hmf6c4qx4c&filter=posts_and_author_threads&includePins=true&limit=30)
Referrer Policy: Ignoring the less restricted referrer policy “origin-when-cross-origin” for the cross-site request: https://chanterelle.us-west.host.bsky.network/xrpc/chat.bsky.convo.listConvos?limit=20 [chat.bsky.convo.listConvos](https://chanterelle.us-west.host.bsky.network/xrpc/chat.bsky.convo.listConvos?limit=20)
Referrer Policy: Ignoring the less restricted referrer policy “origin-when-cross-origin” for the cross-site request: https://chanterelle.us-west.host.bsky.network/xrpc/app.bsky.feed.getAuthorFeed?actor=did%3Aplc%3Aks3gpa6ftoyaq7hmf6c4qx4c&filter=posts_and_author_threads&includePins=true&cursor=2024-12-03T06%3A38%3A20.953Z&limit=30 [app.bsky.feed.getAuthorFeed](https://chanterelle.us-west.host.bsky.network/xrpc/app.bsky.feed.getAuthorFeed?actor=did%3Aplc%3Aks3gpa6ftoyaq7hmf6c4qx4c&filter=posts_and_author_threads&includePins=true&cursor=2024-12-03T06%3A38%3A20.953Z&limit=30)
Referrer Policy: Ignoring the less restricted referrer policy “origin-when-cross-origin” for the cross-site request: https://chanterelle.us-west.host.bsky.network/xrpc/app.bsky.graph.getSuggestedFollowsByActor?actor=did%3Aplc%3Aks3gpa6ftoyaq7hmf6c4qx4c [app.bsky.graph.getSuggestedFollowsByActor](https://chanterelle.us-west.host.bsky.network/xrpc/app.bsky.graph.getSuggestedFollowsByActor?actor=did%3Aplc%3Aks3gpa6ftoyaq7hmf6c4qx4c)
Referrer Policy: Ignoring the less restricted referrer policy “origin-when-cross-origin” for the cross-site request: https://chanterelle.us-west.host.bsky.network/xrpc/app.bsky.feed.getAuthorFeed?actor=did%3Aplc%3Aks3gpa6ftoyaq7hmf6c4qx4c&filter=posts_and_author_threads&includePins=true&cursor=2024-11-27T06%3A42%3A21.165Z&limit=30 [app.bsky.feed.getAuthorFeed](https://chanterelle.us-west.host.bsky.network/xrpc/app.bsky.feed.getAuthorFeed?actor=did%3Aplc%3Aks3gpa6ftoyaq7hmf6c4qx4c&filter=posts_and_author_threads&includePins=true&cursor=2024-11-27T06%3A42%3A21.165Z&limit=30)
Referrer Policy: Ignoring the less restricted referrer policy “origin-when-cross-origin” for the cross-site request: https://chanterelle.us-west.host.bsky.network/xrpc/chat.bsky.convo.listConvos?limit=20 [chat.bsky.convo.listConvos](https://chanterelle.us-west.host.bsky.network/xrpc/chat.bsky.convo.listConvos?limit=20)
Referrer Policy: Ignoring the less restricted referrer policy “origin-when-cross-origin” for the cross-site request: https://chanterelle.us-west.host.bsky.network/xrpc/app.bsky.feed.getAuthorFeed?actor=did%3Aplc%3Aks3gpa6ftoyaq7hmf6c4qx4c&filter=posts_and_author_threads&includePins=true&cursor=2024-11-25T22%3A01%3A56.654Z&limit=30 [app.bsky.feed.getAuthorFeed](https://chanterelle.us-west.host.bsky.network/xrpc/app.bsky.feed.getAuthorFeed?actor=did%3Aplc%3Aks3gpa6ftoyaq7hmf6c4qx4c&filter=posts_and_author_threads&includePins=true&cursor=2024-11-25T22%3A01%3A56.654Z&limit=30)
Attempting to block user: @dieworkwear.bsky.social [index.js:1:8132](moz-extension://1291e947-a461-4651-a346-71bf572e0991/index.js)
Session data retrieved: pdsUrl=https://chanterelle.us-west.host.bsky.network/, did=did:plc:4g43jcw5qenpylbkfulfjgii [index.js:1:8132](moz-extension://1291e947-a461-4651-a346-71bf572e0991/index.js)
Fetching profile for @dieworkwear.bsky.social from URL: https://chanterelle.us-west.host.bsky.network/xrpc/app.bsky.actor.getProfile?actor=dieworkwear.bsky.social [index.js:1:8132](moz-extension://1291e947-a461-4651-a346-71bf572e0991/index.js)
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://chanterelle.us-west.host.bsky.network/xrpc/app.bsky.actor.getProfile?actor=dieworkwear.bsky.social. (Reason: CORS header ‘Origin’ cannot be added).

Error blocking user: TypeError: NetworkError when attempting to fetch resource.
    f moz-extension://1291e947-a461-4651-a346-71bf572e0991/index.js:1
    a moz-extension://1291e947-a461-4651-a346-71bf572e0991/index.js:1
    m moz-extension://1291e947-a461-4651-a346-71bf572e0991/index.js:1
[index.js:1:8170](moz-extension://1291e947-a461-4651-a346-71bf572e0991/index.js)
    d moz-extension://1291e947-a461-4651-a346-71bf572e0991/index.js:1
    m moz-extension://1291e947-a461-4651-a346-71bf572e0991/index.js:1
The resource at “https://bsky.app/static/media/InterVariable.c9f788f6e7ebaec75d7c.ttf” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. [dieworkwear.bsky.social](https://bsky.app/profile/dieworkwear.bsky.social)
The resource at “https://bsky.app/static/media/InterVariable-Italic.55d6a3f35e9b605ba6f4.ttf” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. [dieworkwear.bsky.social](https://bsky.app/profile/dieworkwear.bsky.social)`

**Comment by RoyRiv3r** [comment]
Oh I see the error now, it seems like Bluesky is using different and multiple APIs ...
As you can see [https://chanterelle.us-west.host.bsky.network](https://chanterelle.us-west.host.bsky.network/xrpc/app.bsky.actor.getProfile?actor=dieworkwear.bsky.social) here.

I only have added to the list https://verpa.us-west.host.bsky.network/, It should be easy to fix.

However, I'm not sure how many variants of their API are currently there, so this error will probably repeat. 

I'll make sure to monitor any changes, thank you for the information.

**Comment by RoyRiv3r** [comment]
1.0.5 is up should be fixed, please let me know if it's working, feel free to close the issue if that's the case. :)

**Comment by rapdactyl** [comment]
Looks like it is working now, thank you very much!
